import { IContentModel } from "../models/ContentModel";

export const BorderlineKisilikBozuklugu: IContentModel = {
  mainTitle: "Borderline Kişilik Bozukluğu Nedir?",
  description:
    "Borderline kişilik kavramı,1938 yılında Adolf Stern tarafından ortaya atılmıştır. Borderline kişilik bozukluğu kavramı ise 1975 yılında Otto Kernberg adlı Avusturyalı bir psikiyatrist tarafından tanımlanmıştır. Borderline bozukluğu olan kişilerin öz denetim mekanizmalarında sorun vardır, düşünce ve davranışlarında istikrarsızlık söz konusudur.\n Borderline kişilik bozukluğu olan kişilerde ani ruh hali değişiklikleri görülebilir. Bu bozukluğa sahip kişiler sık sık; hayattaki rollerini, gerçekte kim olduklarını ve ne amaçla yaşadıklarını sorgulayan düşüncelere kapılır. Bu düşüncelerdeki hızlı değişim; kişinin değer yargılarının, ilgi alanlarının da değişmesine yol açar. Borderline bozukluğu olan kişiler, olayları ve durumları keskin bir şekilde değerlendirir. Bu kişilere göre bir olay ya çok iyidir ya da çok kötüdür, ortalama olmaz. Borderline bozukluğu olan kişilerin insanlar hakkındaki fikirleri de sebepsiz yere çabucak değişebilir. Bir gün çok samimi bir arkadaşı olarak gördüğü birine, ertesi gün bir düşmanmış gibi davranabilir. Bu nedenle insanlarla olan ikili ilişkileri istikrarsızdır. Bunların yanı sıra bu kişiler, ikili ilişkilerde yoğun duygular hissedebilir, abartılı davranışlar sergileyebilir.\n Borderline kişilik bozukluğuna neden olan durumlar tam olarak aydınlatılamamış olsa da bazı faktörlerin varlığı, bu rahatsızlığın gelişimine katkıda bulunur. Örneğin genetik temellerin hastalık gelişiminde rol oynadığı düşünülür. Çünkü birinci derece yakınlarında borderline kişilik bozukluğu olan kişilerin, bu hastalığa sahip olma riski artmıştır. Hastalığın gelişimini daha iyi anlamak için yapılan çalışmalarda, sağlıklı bir kişi ile borderline hastası bir kişinin beyinleri arasında yapısal ve işlevsel birtakım farklılıklara rastlanmıştır. Ancak bu farklılıkların hastalık ile arasındaki ilişki henüz tam anlamıyla kurulamamıştır. Sosyal, kültürel ve sosyal etkenler de hastalık gelişiminde etkili oluyor olabilir. Borderline kişilik bozukluğuna sahip kişiler arasında çocuk döneminde ihmal, taciz, terk edilme gibi olaylar yaşayanların sayısı oldukça fazladır. Erken yaşta karşılaşılan bu travmalar da hastalık gelişiminde rol oynayabilir. Psikiyatrik hastalıklar, pek çok farklı etmenin bir araya gelmesi ile ortaya çıkar. Bu nedenle her travma geçiren kişide ya da ailesinde borderline bozukluğu olan herkeste hastalık görülür demek doğru bir yaklaşım olmaz.",
  tags: ["KİŞİLİK BOZUKLUĞU", "BORDERLİNE KİŞİLİK BOZUKLUĞU"],
  lastUpdateDate: new Date("14 Mar 2023"),
  pathName: "borderline-kisilik-bozuklugu",
};
