import { IContentModel } from "../models/ContentModel";

export const PsikodinamikTerapi: IContentModel = {
  mainTitle: "Psikodinamik Terapi Nedir?",
  description: `Dinamik yapıda içselleştirilmiş nesne ilişkilerinin, çocukluk döneminde içe alınmış olan ikili yapıtları daha sonraki hayatımızda davranışlarla tekrarladığımız., Freud’un ifade ettiği gibi, bu da dinamik ekolü oluşturmuştur.`,
  tags: ["TERAPİ", "PSİKODİNAMİK TERAPİ"],
  subContent: [
    {
      title: "Psikodinamik Terapinin Karakteristik Süreçleri Nelerdir?",
      description: `Duygulanıma ve hastanın duygularının ifade edilmesine odaklanmak; Hastanın belli konulardan kaçınmasını ya da terapinin ilerlemesini engelleyen davranışları üzerinde durmak; Hastanın davranış, düşünce, duygu, deneyim ve ilişki örüntülerini tespit etmeye çalışmak; Geçmiş deneyim üzerinde durmak; Hastanın kişilerarası ilişkilerine odaklanmak; Terapötik ilişkiye önem vermek; ve Hastanın arzuları, hayalleri ve fantezilerini ele almak ( Blagys ve Hilsenroth 2000, s.167).`,
    },
    {
      title: "İdeal Psikodinamik Terapinin en karakteristik 20 Maddesi",
      description: `Hastanın rüyaları ve fantezileri tartışılır. Terapist tarafsızdır Terapist terapideki ilişki ile diğer ilişkiler arasında bağlantılar kurar. Terapist hastanın savunmacı manevraları kullanımına işaret eder Terapist hastanın hislerine duyarlı, hastayla aynı frekansta, empatiktir. Terapist ketlenen veya bilinçdışı istek, his veya fikirleri yorumlar. Terapist yargılayıcı olmayan kabul hissi verir. Hasta yeni bir anlayış veya içgörüye ulaşır. Terapi ilişkisine odaklanır. Terapist hasta ile açık ve tutarlı bir tarzda iletişim kurar. Terapist hastanın kabul edilemez gördüğü hislere dikkat çeker (örn. öfke, haset, heyecan). Cinsel hisler ve deneyimler konuşulur. Hastanın seans içindeki davranışı terapist tarafından yeniden formüle edilerek o ana kadar açıkça görülmemiş bir şekilde görülmesi sağlanır. Kendilik imgesi konuşulur. Bebeklik ve çocukluk anıları veya yeniden yapılandırmaları konuşulur. Hastanın hisleri veya algıları geçmişteki durumlar veya davranışlarla bağlantılandırılır. Terapist hastanın deneyim veya davranışında tekrar tekrar ortaya çıkan bir temayı tespit eder. Terapistin söyledikleri hastanın konuşmasını kolaylaştırmayı amaçlar. Terapist hastanın duygu durumu ve duygulanımındaki değişiklikler üzerine yorum yapar. Terapist hastanın suçluluk hislerine odaklanır. Kaynak. Ablın ve Jones’tan (1998) uyarlanmıştır.

      Anne çocuğu yetiştirirken; “annem beni terk edecek” düşüncesi çocukta yerleşirse çocuk histerik olur. Obsesif kişilikte, anne aşırı müdahale etmiştir, her şeye karışmıştır. Narsistik kendiliğin oluşması için ise çocukta sürekli ötekinin aynasına ihtiyaç duyma olacaktır. Prens gibi yetiştirilen çocuk, bu ilgiyi herkesten bekleyecek, bunu bulamayınca da o kişileri harcayacaklar… Gerçek travma nedir; anlamlandıramamaktır.
      
      Histerik kişiliklerde, kaçan kovalanır sık yaşanan bir durumdur. Ama burada temel problem, bireyin çocukken karşı cinsten olan ebeveyniyle sevgi ilişkisini tamamlayamamış olmasıdır. Yani örneğin erkek çocuğu anneye yakınlaşır, ilgi duyar, anneyi sever, aşkım der; anne buna izin verir (normalde engel olmalıdır) ve çocuk böylece histerik olur. Ve büyüdüğünde, sevgi nesnesiyle aşk nesnesini birleştiremez ( hem annesine benzer birini bulmaya çalışabilir, hem de babasına yaptığı şeyin pişmanlığını ömür boyu yaşar. Sıklıkla tam evlenme noktasına geldiğinde, kaçacaktır. Çünkü onun için sevgi nesnesi ile erotik nesnesi aynı yerde birleşemez, birleştiğinde ona hep anneyi hatırlatacaktır!) (kız çocuğu içinde , tersi durum geçerlidir)
      
      Kız çocuğu büyüdüğünde sık sık aldatıyorsa, özellikle evliyken aldatıyorsa, çoğu zaman temelde, bu kız çocuğunun kendi babasıyla yaşadığı ve aşamadığı bir gelişim sürecinin sonucudur. Mesela; kız çocuğu anneyle rekabete girer ve babasını kazanırsa (yani babasıyla birlikte dışarı çıkmak için annesini evde bırakmayı teklif ettiğinde, babası bunu kabul ederse. Kızı bir zafer kazanmış olur, baba tarafından uyarılmıştır ve baba o teklifi kabul ederek kızının bu duygusunu beslemiştir). Yani baba, kızında uyanabilecek ŞEHVET ile ŞEFKAT duygularından, şefkatin oluşmasına zemin hazırlayacak şekilde hareket etmeli, yani kızıyla ilişkisinde anneyi dışlamamış olmalıdır. Çünkü şefkat ile tamamlanırsa o ilişki, kız çocuğu şehveti ileride başka bir erkekle tamamlaması gerektiğini anlar. Ama şehvet ile tamamlanırsa, ileride kız çocuğu kuvvetle muhtemel babasına benzer bir erkek seçmeye çalışacak ya da aldatma temelli ilişkilerde yer alacak. Babayla oluşturulan, o ilişki rol model alınacaktır. Yani özetle, baba, kız çocuğuna fazla flörtöz davranmamalıdır. Çünkü öyle davranırsa, kız çocuğu için hem sevgi nesnesi hem erotik nesne aynı olmuş olur, dolayısıyla ileride yaşayacağı ilişkilerde her seferinde tam evleneceği sırada ilişkiden kaçar, hep kaçar, çünkü her ilişki ona babasıyla yakınlaşmasını hatırlatır.
      
      Narsisizm’in hikayesinde, suda kendi aksini gören, ama ona aşık olamayan, bu yüzden de Tanrılar tarafından cezalandırılan bir kişiden bahsedilir. Yani Tanrıların istediği şey, kişinin, karşısındaki bireyde yani ötekinde kendini bulması ve ona aşık olmasıdır. Yani, bazı görüşlere göre narsisizm varoluşun çekirdeğidir, her insan bu çekirdeğe sahiptir. Narsisizm, kendini beğenme-sevme değildir; kendini beğenme-sevme İHTİYACIDIR. Narsisizm olmadan, kitap yazamazsın. Bu ve benzeri tüm girişimler, narsistik enerjimizden kaynaklanır. Narsistik yapı, olağandır, ama uç noktalara gidilmesi zarar vericidir. Narsistik kırılma = incinme; kişinin toplumdan uzaklaşmasına, içine kapanmasına neden olur. Kliniklerde, pek çoğusu sosyal fobi olarak tanı alır…
      
      Anoreksik kişilerin, genelde kimlik bunalımı yaşayanlar olduğu görülür. Baskıcı- kontrolcü olduğu için kişilik özelliklerinin gelişmesini önleyen ailelerde ya da kopuk aileler de daha sık gözlenir. Böyle kişiler, hayata karşı çaresiz ve etkisiz kaldıkları için, gücü yeten ve kendi kontrolünde olan bedeni üzerinden bir sürece giriyor. Bedenini, kendisine ait tek şey olarak görüyor. Dışarıdaki denetimi sağlayamayınca, kendi bedenini denetlemeye çalışıyor.`,
    },
  ],
  lastUpdateDate: new Date("14 Mar 2023"),
  pathName: "psikodinamik-terapi",
  featuredPost: true,
};
